# Default values for safe-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of safe-stack for `app:` labels
##
nameOverride: ""
## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []


replicaCount: 1

image:
  repository: safeglobal/safe-client-gateway-nest
  tag: latest
  pullPolicy: Always

extraEnv: []

config:
  debug: true
  amqp:
    url: "" # e.g. amqp://guest:guest@rabbitmq:5672/
    exchange: "safe-transaction-service-events"
    queue: "safe-events-service"
  cfgService:
    url: "http://cfg-service-safe-config-service-web"
  txService:
    url: "http://transaction-service-safe-transaction-service-web"
  security:
    authToken: "1234567890"
  redis:
    host: # leave empty unless safe-client-gateway-redis.enabled=true
    port: 6379
  database:
    host: # leave empty if safe-client-gateway-postgresql.enabled=true
    name: "postgres"

web:
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  securityContext: {}
  podSecurityContext: {}
  resources:
    requests:
      memory: "300Mi"
      cpu: "300m"
    limits:
      memory: "600Mi"
      cpu: "600m" 
      
ingress:
  enabled: true
  ingressClassName: nginx
  host: cgw-service.minikube.net
  annotations: 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "OPTIONS, GET, HEAD, DELETE, PUT, POST"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.minikube.net"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Safe-Wallet-Signature,Safe-Wallet-Signature-Timestamp"
  tls:
    enabled: false
    #host: 
    #secretName:

cors:
  enabled: true
  allowOrigins: "https://*.minikube.net"

safe-client-gateway-redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 100Mi
  replica:
    replicaCount: 0

safe-client-gateway-postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        username: postgres
        password: postgres
        database: postgres
  primary:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 100Mi