{{- if .Values.logo.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safe-wallet-web.fullname" . }}-logo
binaryData:
  logo.png: {{ .Files.Get "files/logo.png" | b64enc }}
{{- end }}
